[build]
  base      = "web/memeflow_frontend"
  # generate Prisma client before Next compiles
  command   = "npx prisma generate && npm run build"
  publish   = ".next"
  functions = "netlify/functions"

[build.environment]
  DATABASE_URL = "file:./data/memeflow.db"

[[plugins]]
  package = "@netlify/plugin-nextjs"
