[build]
  command   = "npm run build"   # or "yarn build"
  publish   = ".next"           # where Next places its static assets
  functions = "netlify/functions"

[[plugins]]
    package = "@netlify/nextjs"
    package = "@netlify/plugin-nextjs"